CREATE DATABASE E_VALE;

USE E_VALE;

/*PAIS*/
CREATE TABLE E_VALE.EV_PAIS
(

ID_PAIS			INT	AUTO_INCREMENT,
NOMBRE_PAIS		VARCHAR(30),
PRIMARY KEY (ID_PAIS)

);

/*CIUDAD*/
create	TABLE	E_VALE.EV_CIUDAD
(

ID_CIUDAD		INT	auto_increment,
NOMBRE_CIUDAD	VARCHAR(30),
ID_PAIS			INT,
primary key	(ID_CIUDAD),
foreign key (ID_PAIS) REFERENCES EV_PAIS(ID_PAIS)
ON DELETE CASCADE ON UPDATE CASCADE

);

/*COMUNA*/
create	TABLE	E_VALE.EV_COMUNA
(

ID_COMUNA		INT	auto_increment,
NOMBRE_COMUNA	VARCHAR(30),
ID_CIUDAD		INT,
ID_PAIS			INT,
primary key	(ID_COMUNA),
foreign key (ID_CIUDAD) REFERENCES EV_CIUDAD(ID_CIUDAD)
ON DELETE CASCADE ON UPDATE CASCADE,
foreign key (ID_PAIS) REFERENCES EV_PAIS(ID_PAIS)
ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE	TABLE 	E_VALE.EV_COLABORADOR
(

ID_COLABORADOR			INT auto_increment,
RUT_COLABORADOR			VARCHAR(10),
NOMBRES_COLABORADOR		VARCHAR(100),
PATERNO_COLABORADOR		VARCHAR(50),
MATERNO_COLABORADOR		VARCHAR(50),
DIRECCION_COLABORADOR	VARCHAR(100),
ID_COMUNA				INT,
ID_CIUDAD				INT,
ID_PAIS					INT,
PRIMARY KEY(ID_COLABORADOR),
FOREIGN KEY(ID_COMUNA)	REFERENCES	EV_COMUNA(ID_COMUNA)
ON DELETE CASCADE ON UPDATE CASCADE
);


