SELECT EV_FUNC_ENTRAR('J_COURBIS_CAP','JULIOGCOURBIS');

select	encrypt('hola','chao');

UPDATE E_VALE.EV_USUARIO
SET PASS	=	aes_encrypt('JULIOCOURBIS','SQL')
WHERE	ID_USUARIO	=	1;
    
SELECT aes_decrypt(PASS,'JULIOCOURBIS') FROM EV_USUARIO;

SELECT	*
FROM	EV_USUARIO;

SELECT	1
FROM	EV_USUARIO US
WHERE	US.USUARIO			=	'J_COURBIS_CAP'
	AND	US.PASS				=	'SQL'
    AND	US.FLG_VIGENTE		=	1;
    
SELECT CAST(AES_DECRYPT(pass, 'SQL') AS CHAR(50)) pass 
FROM   EV_USUARIO   US
WHERE	US.USUARIO='J_COURBIS_CAP'